ecs_cluster_name = "luqman-ecs-cluster-dev"
ecs_service_name = "luqman-ecs-service-dev"
ecs_task_defn_family = "luqman-ecs-task-def-dev"
ecs_container_name = "luqman-container-dev"
ecs_port_name = "luqman-3000-tcp-dev"