ecs_cluster_name = "luqman-ecs-cluster-uat"
ecs_service_name = "luqman-ecs-service-uat"
ecs_task_defn_family = "luqman-ecs-task-def-uat"
ecs_container_name = "luqman-container-uat"
ecs_port_name = "luqman-3000-tcp-uat"