ecs_cluster_name = "luqman-ecs-cluster-prod"
ecs_service_name = "luqman-ecs-service-prod"
ecs_task_defn_family = "luqman-ecs-task-def-prod"
ecs_container_name = "luqman-container-prod"
ecs_port_name = "luqman-3000-tcp-prod"